### ISSUE TITLE
reported FAIL about glyphsname

### ISSUE THREAD

**Issue by RosaWagner** [dy/linefont#10]
The glyphs don't seem to have production names

🔥 FAIL: Glyph names are all valid? ([com.google.fonts/check/valid_glyphnames](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames))
🔥 FAIL The following glyph names do not comply with naming conventions: to-0, to-1, to-10, to-100, to-101, to-102, to-103, to-104, to-105, to-106 and 118 more.
Use -F or --full-lists to disable shortening of long lists.

**Comment by dy** [comment]
Ok, fixed glyphs naming. Thank you!
