### ISSUE TITLE
Support ASCII code points

### ISSUE THREAD

**Issue by mmiszy** [dy/linefont#2]
Would it be possible to add support for ASCII codepoints instead of the `U+0100-017F` unicode range?
ASCII codes 97-122 and 65-90 in particular.

My use case is adding fancy underline to a text simply by duplicating it and using `linefont`.

Thanks!

**Comment by dy** [comment]
What stops you from using U+0100 characters? Is that easier to experiment via ascii? I think you can use 0-10 characters for simple range.

**Comment by dy** [comment]
Added in v2, now supports a-Z or 0-9
