### ISSUE TITLE
STAT and instances

### ISSUE THREAD

**Issue by RosaWagner** [dy/linefont#9]
If possible you could tweak the value to range:
- wght(100,900) default 400. You can map value 5 to user value 100, and 400 to 900
- wdth(25,200) default at 100

wdth and wght being common axes, you don't need to include the stat entry in config.yaml, gftools would build it correctly.

Instances in FVAR table should follow this: [#6244 ](https://googlefonts.github.io/gf-guide/variable.html#wght)

**Comment by dy** [comment]
Ok, I will adjust defaults, but as for mapping to 100..900 - I had that initially, but removed in order to be compatible with wavefont. Eg. if user switches font from wave- to line- the weight keeps persistent.

**Comment by RosaWagner** [comment]
The thing is in linefont is that the larger weight looks extremely heavy compared to wavefont. If you want consistency, I'd rather change wavefont to range from 100 to 900 (which is still possible, a problem in the API prevent to push it in sandbox for now), it would also gives more instances/flexibility to users.

**Comment by dy** [comment]
Makes sense. Weight=400 for wavefont looks like super-heavy 
<img width="1051" alt="image" src="https://github.com/dy/linefont/assets/300067/4620bd25-a0ea-4267-92f0-4542d05de679">
I guess I can extend both to 100..900

**Comment by dy** [comment]
Ok, I have updated both fonts to support 100..900 range (maps to 5..200 ups internally).
Also removed weight from `stat` config.
Not sure how to provide defaults in designspace - if I indicate `default=400` it requires a master with that weight to be present. But any additional master increases font size up to 30%. I'd prefer to keep default axis values to min values instead.
@RosaWagner

**Comment by RosaWagner** [comment]
> Also removed weight from stat config.

Nope, if the stat entry is specified (such as when there are custom axis) then it has to be complete. The entire entry can me removed, only when all the axes can be generated by gftools (wdth, wght, ital).

**Comment by dy** [comment]
Got it. Updated, thank you @RosaWagner

**Comment by RosaWagner** [comment]
Since you are keeping the minimal values as default we would need the font to be named after the origin:

font name: Linefont SuperCondensed
style: Thin

**Comment by RosaWagner** [comment]
The instances don't change cause they are at 100 (normal), but the Master Source yes it should be `Linefont SuperCondensed`

In plist I guess it should be:
  ...
  <key>familyName</key>
  <string>Linefont SuperCondensed</string>
  <key>styleName</key>
  <string>Thin</string>
  <key>postscriptFontName</key>
  <string>LinefontSuperCondensed-Thin</string>
  <key>postscriptFullName</key>
  <string>Linefont SuperCondensed Thin</string>
  <key>postscriptWeightName</key>
  <string>Thin</string>
  ...

For the error, can you open an issue in fontmake and tag me in it? I gonna be in holidays in a couple of days and it's better if the maintainer communicate with you directly

**Comment by dy** [comment]
@RosaWagner it seems default width value here isn't necessarily SuperCondensed - I can pick `wdth` to be 100, so the SuperCondensed isn't necessary I suppose?

**Comment by RosaWagner** [comment]
Yes that would be even better
